name: Build LaTeX Resume

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: resume/resume.tex   # 👈 point to your .tex file
          working_directory: resume      # 👈 run inside the resume/ folder

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume/resume.pdf   # 👈 your compiled PDF