name: Build & Deploy Resumess

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        resume: [ "resume/de/resume.tex", "resume/ds/resume.tex", "resume/sde/resume.tex" ]

    steps:
      - uses: actions/checkout@v3

      - name: Compile ${{ matrix.resume }}
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.resume }}

      - name: Move PDF to public folder
        run: |
          mkdir -p public/${{ matrix.resume }}
          mv $(dirname ${{ matrix.resume }})/*.pdf public/${{ matrix.resume }}/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4