name: Build and Publish Resumes

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Loop through each resume folder and compile
      - name: Compile all resumes
        uses: dante-ev/latex-action@latest
        with:
          root_file: |
            resume/de/resume.tex
            resume/ds/resume.tex
            resume/sde/resume.tex

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes-pdf
          path: |
            resume/de/resume.pdf
            resume/ds/resume.pdf
            resume/sde/resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PDFs artifact
        uses: actions/download-artifact@v4
        with:
          name: resumes-pdf
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public