name: Build and Publish Resume

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: dante-ev/latex-action@latest
        with:
          working_directory: resume    # folder containing resume.tex
          root_file: resume.tex        # name of the tex file
          output_directory: ../public  # outputs PDF to repo-root/public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public