name: Build and Publish Resume

on:
  push:
    branches: [ master ]
  workflow_dispatch:   # allows manual run too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up LaTeX
        uses: dante-ev/latex-action@v2
        with:
          root_file: resume/resume.tex
          working_directory: resume

      - name: Move PDF to publish folder
        run: |
          mkdir public
          cp resume/resume.pdf public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public