name: Build and Deploy Resumes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        run: sudo apt-get update && sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Build SDE Resume
        run: |
          cd resume/sde
          pdflatex resume.tex
          mv resume.pdf ../../sde.pdf

      - name: Build DS Resume
        run: |
          cd resume/ds
          pdflatex resume.tex
          mv resume.pdf ../../ds.pdf

      - name: Build DE Resume
        run: |
          cd resume/de
          pdflatex resume.tex
          mv resume.pdf ../../de.pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true