name: Build and Publish Resume

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    outputs:
      pdf_path: ${{ steps.upload.outputs.artifact-name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest

      - name: Compile LaTeX
        uses: dante-ev/latex-action@latest
        with:
          working_directory: resume
          root_file: resume.tex
          output_directory: ./build

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@latest
        id: upload
        with:
          name: resume-pdf
          path: build/resume.pdf

  deploy:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@latest
        with:
          name: resume-pdf
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public